### ISSUE TITLE
还是可以破解asar包啊

### ISSUE THREAD

**Issue by wall3001** [alex8088/electron-vite-bytecode-example#1]
main: {
    plugins: [externalizeDepsPlugin(), bytecodePlugin()]
  },
  preload: {
    plugins: [externalizeDepsPlugin(), bytecodePlugin()], 
为什么还是可以破解asar包啊？

**Comment by alex8088** [comment]
字节码加密和asar无关，加密的是你的代码不是asar包，解压asar，代码文件仍是字节码加密过的。

**Comment by wall3001** [comment]
解压后的代码也没有加密

**Comment by alex8088** [comment]
执行 electron-vite preview 后 out 目录下 main 是否 有jsc文件。如果没有就是没有正确使用。

![image](https://github.com/alex8088/electron-vite-bytecode-example/assets/25053004/1318a4c8-9036-427a-bd84-f88a8655537a)
![image](https://github.com/alex8088/electron-vite-bytecode-example/assets/25053004/28fb016a-7b0e-4a57-8ba3-b526af7af830)

**Comment by alex8088** [comment]
建议通常此demo自己去测试

**Comment by wall3001** [comment]
我是直接打包的    "build:win": "electron-vite build --mode prod && electron-builder --win --config", 没有jsc文件， out目录里面有

**Comment by wall3001** [comment]
解压asar包后，还是有src在里面,这里面还是源码，是打包配置问题吗？

**Comment by alex8088** [comment]
electron-builder配置，不用分发源代码目录

![image](https://github.com/alex8088/electron-vite-bytecode-example/assets/25053004/c4e3267b-f44a-4350-8757-abe82887f7de)

**Comment by wall3001** [comment]
好的，谢谢大佬！
