### ISSUE TITLE
preload 加密后运行不了了

### ISSUE THREAD

**Issue by wall3001** [alex8088/electron-vite-bytecode-example#2]
![image](https://github.com/alex8088/electron-vite-bytecode-example/assets/16306014/0107bd78-db15-4619-9815-e1a683243c94)

**Comment by alex8088** [comment]
bytecode 不支持渲染进程

**Comment by wall3001** [comment]
我没加密renderer，是加密preload脚本的

**Comment by wall3001** [comment]
哦，这个脚本是要在渲染进程执行的，也是不能使用的是吗？

**Comment by wall3001** [comment]
webview.executeJavaScript 通过这个执行的

**Comment by alex8088** [comment]
preload 是可以的，preload怎么绑定。webview.executeJavaScript 是执行脚本，不支持字节码的

**Comment by wall3001** [comment]
好的
