### ISSUE TITLE
vanilla?

### ISSUE THREAD

**Issue by davuttemel** [alex8088/electron-vite-bytecode-example#3]
I make an app with electron. main.js index.js preload.js login.html and index.html. but I want to my project byte code. how can I protection my codes. please help me.

**Comment by alex8088** [comment]
The vanilla template is an extremely simple template that does not combine any building tools ([electron-vite](https://electron-vite.org)) and uses cjs syntax directly. You can use vanilla-ts template and refactor to js.

**Comment by alex8088** [comment]
`npm create @quick-start/electron`

**Comment by alex8088** [comment]
vanilla template support now
